#!/usr/bin/env bash
read -p "Press ENTER to continue"

./remove-legacy

rm -rf ./account-generator
rm -rf ./build
rm -rf ./polskahook
rm -rf ./polskahook-ipc-server
rm -rf ./polskahook-ipc-web-panel
rm -rf ./just-disable-vac
rm -rf ./user_instances
rm -rf ./polskabot-database
sudo rm -rf /opt/cathook/ipc
sudo rm /opt/cathook/bin/libcathook-textmode.so
